; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32@6.5.0
board = esp32doit-devkit-v1

framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
lib_deps =
    https://github.com/hoeken/PsychicHttp.git#e878a9f0dadfbf0faaf7ef478f3e4d1ca3079194
	https://github.com/HowardsPlayPen/ElegantOTA.git#0caecf54f9914d6ec14d8009e9ca8bb3f9504b07
	knolleary/PubSubClient@2.8
	https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library.git#f9a49801f8961d41b7e17812fe6119c49f4c5a13
	intrbiz/Crypto@1.0.0
lib_ldf_mode = deep+
#build_flags = -D CUSTOM_GPIOS 				#uncomment this line if you'd like to enable customgpio support
build_flags = -D ELEGANTOTA_USE_PSYCHIC=1
			  -D PSY_ENABLE_SSL				# uncomment to enable SSH encryption
